### ISSUE TITLE
Cookie policy settings

### ISSUE THREAD

**Issue by l4ngur** [nuxt-community/google-analytics-module#103]
Hi, please, is it possible to set GA cookie policy within this module? I can't figure out how.

https://developers.google.com/analytics/devguides/collection/analyticsjs/cookies-user-id#configuring_cookie_field_settings

Thank you very much.
Vaclav

**Comment by ricardogobbosouza** [comment]
Hi @l4ngur 

Unfortunately, there is no way, as it is defined as `auto` by [`vue-analytics`](https://github.com/MatteoGabriele/vue-analytics) that stopped receiving feature requests.
https://github.com/MatteoGabriele/vue-analytics/blob/master/src/create-trackers.js#L29

See the future of the module at https://github.com/nuxt-community/gtm-module/issues/82
