### ISSUE TITLE
Is this module still up to date? Can't set it up with new Google Analytics ID

### ISSUE THREAD

**Issue by emsitkowski** [nuxt-community/google-analytics-module#104]
I have problem with setting up this (or any) module with the new Google Analytics ID number format, which is G-XXXXXXXXXX - not UA-XXXXXXXX-X.
It just doesn't work.

**Comment by MatteoGabriele** [comment]
the answer is no and it's also pinned in the issue list

**Comment by MatteoGabriele** [comment]
you need to use a gtag compatible package
