### ISSUE TITLE
Update Docs to note that this module only works with Universal Analytics and not with the new GA4

### ISSUE THREAD

**Issue by ctwhome** [nuxt-community/google-analytics-module#106]
Getting more info from https://stackoverflow.com/questions/64612031/setup-google-analytics-4-in-nuxt-js

**Comment by IlanVivanco** [comment]
Or even better, make it work with the Universal Analytics.

**Comment by dimas-ibnu** [comment]
Really waiting for this plugin can support GA4

**Comment by MikesGlitch** [comment]
I've implemented this in my own blog using the [vue-gtag](https://matteo-gabriele.gitbook.io/vue-gtag/plugin-options) library.  You can use my code as a reference until there's a package for it (if anyone's interested). 

The code is here: https://github.com/MikesGlitch/mikesglitch.com/tree/main/googleanalytics

It's literally just a wrapper around the vue-gtag library

**Comment by rlam3** [comment]
Do we know if we can run GA4 and GA3 simultaneously? Or is this a bad idea?

**Comment by ricardogobbosouza** [comment]
@IlanVivanco, @dimas-ibnu 
Please see #94
