### ISSUE TITLE
Duplicating pageviews

### ISSUE THREAD

**Issue by guiwestrup** [nuxt-community/google-analytics-module#107]
I'm using in pages the this.$ga.page() on the mounted() function, every page change he's shoot two pageviews:
Using this plugin for debug: https://chrome.google.com/webstore/detail/google-analytics-debugger/jnkmfdileelhofjcijamephohjechhna

![image](https://user-images.githubusercontent.com/23106111/108114707-ea583300-7077-11eb-87fa-9393de1ac301.png)

![image](https://user-images.githubusercontent.com/23106111/108114613-c7c61a00-7077-11eb-9d97-6657be1b2a44.png)

**Comment by sharing-tech** [comment]
I'm having the same problem.
Changed to manual because I want to use custom dimensions.
Duplicate.

**Comment by guiwestrup** [comment]
How can i deactivate the automatic tracking?

I already use the manual way, in method mounted():

` this.$ga.page({
      page: this.$router.currentRoute.path,
      title: this.seo.title,
      location: window.location.href
    })
`

**Comment by sharing-tech** [comment]
I solved this problem by installing vue-analytics, which is the original version of this module.
https://github.com/MatteoGabriele/vue-analytics
https://matteogabriele.gitbooks.io/vue-analytics/content/

**Comment by guiwestrup** [comment]
> I uninstalled this module and installed the original vue-analytics, which solved this problem.
> https://github.com/MatteoGabriele/vue-analytics
> https://matteogabriele.gitbooks.io/vue-analytics/content/

This fixed
Duplicate of #

**Comment by MathieuPcz** [comment]
To avoid duplication of routes, you can add the ignoreRoutes attribute to your configuration.

`googleAnalytics: {
        ignoreRoutes: ['route_name', 'path_of_route']
 },`

this will ignore these routes during the automatic push. It will therefore be necessary to manage it manually for these paths
Ex : 
 
` this.$ga.page(this.$route.fullPath)`
