### ISSUE TITLE
Add support for nuxt 3

### ISSUE THREAD

**Issue by cayekple** [nuxt-community/google-analytics-module#127]
Adding the google analytics module to nuxt 3 generates the following errors: 

-  ERROR  Error compiling template
-  ERROR  Cannot start nuxt:  serialize is not defined

Here my nuxt config

```js
import { defineNuxtConfig } from 'nuxt3'

// https://v3.nuxtjs.org/docs/directory-structure/nuxt.config
export default defineNuxtConfig({
    css: ["~/assets/css/styles.css"],
    build: {
        postcss: {
            postcssOptions: require("./postcss.config.js"),
        },
    },
    modules: [
        ['@nuxtjs/google-analytics', { ua: 'X1234567' }],
    ]
})
```

**Comment by afiorenza** [comment]
@cayekple Good morning sr. I am facing the same issue, were you able to find a workaround? 

Thanks  in advance.

**Comment by cayekple** [comment]
@afiorenza Yes, I changed the package to ``yarn add vue-gtag-next``, then I created ``vue-gtag.client.js`` in the *plugins* folder at the project root.

### vue-gtag.client.js
```
import { defineNuxtPlugin } from '#app'
import VueGtag from 'vue-gtag-next'

export default defineNuxtPlugin((nuxtApp) => {
  const getGDPR = localStorage.getItem('GDPR:accepted');
  nuxtApp.vueApp.use(VueGtag, {
    property: {
      id: 'G-XXXXXXXXX
    },
    appName: 'APP NAME',
    enabled: getGDPR === 'true',
    pageTrackerScreenviewEnabled: true
  }, nuxtApp.vueApp.router);
});
```

**Comment by billymaulana** [comment]
https://v3.nuxtjs.org/guide/directory-structure/plugins/

**Comment by digitalcortex** [comment]
> For nuxt 3 RC 11, the below code works fine.
> 
> Create `ga.js` file in `plugins` folder. No need to import or change anything in `nuxt.config.js`. You can name anything actually. I have named it `ga.js`.
> 
> ```js
> import VueGtag from 'vue-gtag'
> 
> export default defineNuxtPlugin((nuxtApp) => {
>     nuxtApp.vueApp.use(VueGtag, {
>         config: {
>             id: 'GA_MEASUREMENT_ID',
>         },
>     }, nuxtApp.$router)
> })
> ```

Does it automatically track route changes?

**Comment by retroriff** [comment]
@adarshmadrech Does it work with GA4?

**Comment by retroriff** [comment]
@digitalcortex I tested it and it does not track route changes.

**Comment by digitalcortex** [comment]
> @digitalcortex I tested it and it does not track route changes.

do you mean vue-gtag or google-analytics-module?

**Comment by retroriff** [comment]
I meant vue-gtag but I was wrong. I checked it again and it tracks route changes :)

**Comment by notflip** [comment]
@retroriff @digitalcortex What version of vue-gtag do you have installed for the script above to work?

**Comment by digitalcortex** [comment]
> @retroriff @adarshmadrecha What version of vue-gtag do you have installed for the script above to work?

vue-gtag@2.0.1

**Comment by notflip** [comment]
@digitalcortex Thanks! Did you manage to access the $gtag variable? I want to send events using $gtag.event() but $gtag is undefined using the method above

**Comment by digitalcortex** [comment]
> @digitalcortex Thanks! Did you manage to access the $gtag variable? I want to send events using $gtag.event() but $gtag is undefined using the method above

Haven't tried going that deep yet. I suspect that vue-gtag doesn't give access to the instance of Google Analytics

**Comment by YosefMets** [comment]
@adarshmadrecha @retroriff @digitalcortex
I am trying to use `vue-gtag`. After adding `plugins/ga.js` `page-view` works. But I don't get any effect from `event`:
```
import { event } from 'vue-gtag'

const addToCart = () => {
  event('add_to_cart', {...});
}
```
When I'm adding item to cart nothing's happened in the Googlу Analytics. There is also no new request in the "Network". But in `window.dataLayer` added a new data `['event', 'add_to_cart', {…}, ...]`

What am I doing wrong?

**Comment by theoephraim** [comment]
for anyone else ending up here trying to get nuxt 3 + GA tracking set up...

For me at the moment with Nuxt 3, installing `vue-gtag-next` with the example above did not work fully, because the router was not accessible via `nuxtApp.vueApp.router`

I had to add some code in `app.vue` to connect it to the router.

In `plugins/ga.js`
```
import { defineNuxtPlugin } from "#app";
import VueGtag from "vue-gtag-next";

export default defineNuxtPlugin((nuxtApp) => {
  nuxtApp.vueApp.use(VueGtag, {
    property: { id: "G-XXXXXXX" },
  });
});
```

In `app.vue`
```
import { trackRouter } from "vue-gtag-next";
const router = useRouter();
trackRouter(router);
```

**Comment by dapug** [comment]
> ```
> import { trackRouter } from "vue-gtag-next";
> const router = useRouter();
> trackRouter(router);
> ```

useRouter(); is not accessible either, and I get a 500 error, `nuxt instance unavailable`.

I don't see why we should need to add that, nothing in the (non-existant v3) docs mentions a peep.  Furthermore, none of the examples others have posted is working.  I've got a brand new Nuxt 3 app with bare bones stuff, hello-world level here, and simply cannot get Google Analytics working. If it is, then documentation, setup, examples, etc are woefully lacking.  Are we sure this issue should be closed?

**Comment by theoephraim** [comment]
@dapug For me if I didn't call trackRouter, it would load the GA script, but it would not track pageviews on SPA/pushstate route changes. Some other examples I saw included passing the router as a 3rd argument to `vueApp.use`, but that didn't seem to work right for me either. I actually ended up putting the `trackRouter(useRouter())` call in the plugin itself and that is working for me.

Make sure you are on latest versions of everything - it all seems to be very much in flux...

**Comment by dapug** [comment]
ok, I'm not even seeing the GA script load, so I think I'm hung up on something even more simple here.  Indeed, it is all in flux.

**Comment by theoephraim** [comment]
@dapug - make sure you turn off ad blocking extensions too... was debugging for a while until I realized 😵‍💫

**Comment by anavalo** [comment]
This seems to work for me:
<script>
`useHead({
  script: [
    {
      src: 'https://www.googletagmanager.com/gtag/js?id=G-YOUR-TAG',
      async: true,
    },
    {
      innerHTML: `
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'G-YOUR-TAG');
      `,
      type: 'text/javascript',
    },
  ],
});
</script>`

**Comment by brunodeangelis** [comment]
> This seems to work for me:
> 
> ```
> <script>
> useHead({
>   script: [
>     {
>       src: 'https://www.googletagmanager.com/gtag/js?id=G-YOUR-TAG',
>       async: true,
>     },
>     {
>       innerHTML: `
>       window.dataLayer = window.dataLayer || [];
>       function gtag(){dataLayer.push(arguments);}
>       gtag('js', new Date());
> 
>       gtag('config', 'G-YOUR-TAG');
>       `,
>       type: 'text/javascript',
>     },
>   ],
> });
> </script>
> ```

Could you confirm this tracks route changes? I'm not sure it does.

**Comment by notflip** [comment]
> > This seems to work for me:
> > ```
> > <script>
> > useHead({
> >   script: [
> >     {
> >       src: 'https://www.googletagmanager.com/gtag/js?id=G-YOUR-TAG',
> >       async: true,
> >     },
> >     {
> >       innerHTML: `
> >       window.dataLayer = window.dataLayer || [];
> >       function gtag(){dataLayer.push(arguments);}
> >       gtag('js', new Date());
> > 
> >       gtag('config', 'G-YOUR-TAG');
> >       `,
> >       type: 'text/javascript',
> >     },
> >   ],
> > });
> > </script>
> > ```
> 
> Could you confirm this tracks route changes? I'm not sure it does.

I can't imagine it does, how is this even connected to the Vue router?

**Comment by brunodeangelis** [comment]
I found this new module
https://github.com/johannschopplich/nuxt-gtag

the author states:

> Ensure that the Enhanced measurement feature is enabled to allow GA4 to automatically track page views in your Single Page Application.
> 
> To enable this feature, go to your Google Analytics 4 account, then navigate to "Admin" > "Data Streams" > "Web" > "Enhanced measurement settings." In this section, make sure the "Page views" toggle is enabled. Enabling the "Page views" toggle allows GA4 to track page changes based on browser history events in your Single Page Application.

so following this I assume that even without connecting to the Vue Router, gtag might be intelligent enough to detect route changes by itself? Don't know if this new module connects to the router, haven't looked at the code yet.
